# Generated by Django 4.2 on 2023-04-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_gadgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImage',
            field=models.ImageField(null=True, upload_to='upload/'),
        ),
    ]
