# Generated by Django 4.2 on 2023-04-12 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_gadgets', '0005_alter_product_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productImage',
            new_name='productImage1',
        ),
    ]
