# Generated by Django 4.2 on 2023-04-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_gadgets', '0006_rename_productimage_product_productimage1'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brandStatus',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
