# Generated by Django 4.2 on 2023-04-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_gadgets', '0007_brand_brandstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brandStatus',
            field=models.BooleanField(default=True),
        ),
    ]
