# Generated by Django 4.2 on 2023-04-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_gadgets', '0009_alter_product_productimage1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImage1',
            field=models.FileField(upload_to='upload/'),
        ),
    ]
