# Generated by Django 4.2 on 2023-04-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_gadgets', '0010_alter_product_productimage1'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='upload/')),
            ],
            options={
                'db_table': 'addfile',
            },
        ),
    ]
