# Generated by Django 4.2 on 2023-04-14 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_gadgets', '0012_product_productimage2_alter_product_productimage1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comind',
        ),
    ]
