# Generated by Django 4.2 on 2023-04-14 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_gadgets', '0013_delete_comind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productImage2',
        ),
    ]
