# Generated by Django 4.2 on 2023-04-17 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_gadgets', '0016_product_productimage3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddFile',
        ),
    ]
