# Generated by Django 4.2 on 2023-04-17 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_gadgets', '0017_delete_addfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='vendorProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_gadgets.product'),
        ),
    ]
