# Generated by Django 4.2 on 2023-04-17 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_gadgets', '0019_rename_vendorproduct_cart_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Product',
            new_name='product',
        ),
    ]
