# Generated by Django 4.2 on 2023-04-26 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_gadgets', '0022_rename_product_cart_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='stateName',
            new_name='name',
        ),
    ]
