# Generated by Django 4.2 on 2023-04-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_address_user_city_user_comment_user_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
